version: '3'

services:
  #Database
  db:
    image: mysql:5.7
    volumes: 
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: laravel
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel
    networks:
      - gcmtest
  #PhpMyAdmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '1110:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: testas
    networks:
      - gcmtest
  #WEB
  web:
    depends_on:
      - db
    image: php:8.1.5-apache
    ports:
      - '8110:80'
    restart: always
    volumes: 
      - './:/var/www/html'
    networks:
      - gcmtest
networks:
  gcmtest:
volumes:
  db_data: